language: java

sudo: required

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report

cache:
  directories:
  - $HOME/.m2
